[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "smartplaybuddy"
version = "0.1.0"
description = "A Python client for SmartPlayBuddy gamepad control."
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "websockets",
    "pyautogui",
    "keyring",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
smtplay = "smartplaybuddy.client:main"
